apiVersion: v2
name: mysql
description: MySQL chart with PVC support
type: application
version: 1.0.1
appVersion: "8.4"
keywords:
  - mysql
  - database
  - kubernetes
home: https://github.com/dev-krishan-dhaka/platform-helm-charts
maintainers:
  - name: dev-krishan-dhaka
    email: devdhaka2341@gmail.com
