apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.mysql.name }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.mysql.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.mysql.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.mysql.name }}
    spec:
      containers:
      - name: {{ .Values.mysql.name }}
        image: "{{ .Values.mysql.image.repository }}:{{ .Values.mysql.image.tag }}"
        ports:
        - containerPort: {{ .Values.mysql.port }}
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: MYSQL_ROOT_PASSWORD
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: MYSQL_DATABASE
        resources:
          requests:
            cpu: {{ .Values.mysql.resources.requests.cpu }}
            memory: {{ .Values.mysql.resources.requests.memory }}
          limits:
            cpu: {{ .Values.mysql.resources.limits.cpu }}
            memory: {{ .Values.mysql.resources.limits.memory }}
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: mysql-storage
      volumes:
      - name: mysql-storage
        {{- if .Values.mysql.pvc.enabled }}
        persistentVolumeClaim:
          claimName: mysql-pvc
        {{- else }}
        emptyDir: {}
        {{- end }}
