apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: {{ .Values.mysql.credentials.rootPassword }}
  MYSQL_DATABASE: {{ .Values.mysql.credentials.database }}
